import React, { Fragment, ReactElement } from 'react';
import Head from 'next/head';
import Nav from '../components/nav/nav';

export default function Layout({ children }: any) {
	return (
		<Fragment>
			<Head>
				<title>Fleming Pictures</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='stylesheet'
					href='https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.compat.css'
				/>

				<link
					href='https://fonts.googleapis.com/icon?family=Material+Icons'
					rel='stylesheet'></link>
				<link rel='icon' href='/favicon.ico' />
				<link
					rel='stylesheet'
					href='https://use.fontawesome.com/releases/v5.15.4/css/all.css'
					integrity='sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm'
					crossOrigin='anonymous'></link>
			</Head>
			<Nav />
			<main>{children}</main>
		</Fragment>
	);
}
